version: 1.0.3.{build}
os: Visual Studio 2022
configuration: Debug
platform: Any CPU

branches:
  only:
  - master

skip_tags: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: CtNjB3/AUTKeFrXmEpR71u6zUBqp2z1/bESLf1LRoZvIQhRnuJEqc5GXELWVHKMI

install:
  - cmd: nuget restore HtmlKit.sln

build:
  project: HtmlKit.sln
  verbosity: minimal

test_script:
- ps: scripts\coveralls.ps1
